### PR TITLE
fix DeprecationWarning/SyntaxError due to invalid escape sequences

### PR DESCRIPTION
**Pull request by niklasb**
Python 3.X (I believe it was 3.6) deprecated the use of invalid escape sequences. For example, with -Werror:

```
.tox/env/lib/python3.8/site-packages/mailchimp3/baseapi.py:8: in <module>
    from mailchimp3.helpers import merge_results
E     File "/app/.tox/env/lib/python3.8/site-packages/mailchimp3/helpers.py", line 81
E       u"(?:\S+(?::\S*)?@)?"
E       ^
E   SyntaxError: invalid escape sequence \S
```

this fixes the string literals

### CODE REVIEW

**Comment by MartinThoma** [comment]
@charlesthk Is anything missing or unclear for this PR?

**Comment by stephenross** [comment]
@MartinThoma Please update the various other files to bump the version (both README files and the setup file)

**Comment by MT-Cash** [comment]
@stephenross Ok: https://github.com/VingtCinq/python-mailchimp/pull/241

**Comment by MT-Cash** [comment]
@niklasb It was merged https://github.com/VingtCinq/python-mailchimp/pull/241 :tada:

**Pull request closed without merging**
