### PR TITLE
Issue 132

### PR DESCRIPTION
**Pull request by stephenross**
This PR covers issues #119, #132, and #133. This also covers changes requested by PR #92. It is planned to add the changes from PR #131 and complete the request from issue #107 before merging this PR. Please check this code while I write/merge the rest for any issues or errors.

### CODE REVIEW

**Comment by charlesthk** [comment]
@stephenross thanks for this huge work. I have reviewed all your commits and everything just look fine to me.

Sorry for the delay, I haven't seen that I was a reviewer of this.

I let you merge and I will push to PyPi.

Thanks.

**Comment by stephenross** [comment]
I am not yet done and will be rebasing it later as well as adding the other mentioned changes. This has sadly fallen on the side for the last few weeks.

**Comment by stephenross** [comment]
Gonna update this probably tomorrow since I see you are touching all of the things and mentioning this, plus it has been way too long

**Comment by stephenross** [comment]
This should resolve #92, #107, #119, #132, and #133. #131 was resolved to master prior to this release. Updates to add some of the additional functionality requested such as batch webhook serializing will need to be built on this. Please verify and merge.

**Comment by stephenross** [comment]
@charlesthk Can you please verify and then release?

**Pull request merged**
