### PR TITLE
add mailchimp3.client logging

### PR DESCRIPTION
**Pull request by tysonholub**
this PR adds a generic _make_requests method to capture logging on all client requests/responses

```python
import logging
logger = logging.getLogger('mailchimp3.client')
logger.addHandler(some_log_file)
```

### CODE REVIEW

**Comment by tysonholub** [comment]
Hi, just following up on this PR. Thanks!

**Comment by tysonholub** [comment]
Added additional commit to include support for request hooks into client

**Comment by stephenross** [comment]
This looks good. Please update the documentation found in the README files to indicate this new functionality, and update the version number of the app in both README files and the setup file. Also include a small section about how to access the logs in case someone has never used that form of logging before, though a link to the official documentation for it is also good. Once all of that is wrapped, we can merge this in and bug Charles to get it on PyPi

**Comment by tysonholub** [comment]
updated docs and bumped version to 2.0.16

**Comment by stephenross** [comment]
@charlesthk The changes have been merged and are ready for a vacation at PyPi resort

**Pull request merged**
